{
    "name": "Asset Management",
    "version": "1.0",
    "summary": "Comprehensive Asset & CAFM Management",
    "description": """
     Standalone Asset Management app
    """,
    'author': 'Baramej® Business and Digital Technology Center LLC',
    'website': 'https://baramej.io/en',
    "category": "Operations/Assets",
    "depends": [
        "account",
        "account_asset",
        "mail",
        "maintenance",
        "stock",
        "hr",
        "helpdesk",
        "website",
        "sale_management",
        "purchase",
    ],
    "data": [
        'security/asset_security.xml',
        "security/ir.model.access.csv",

        "views/asset_views.xml",
        "views/asset_location_views.xml",
        "views/report_maintenance_task.xml",
        "views/asset_maintenance_views.xml",
        "views/asset_service_ticket_views.xml",
        "views/cafm_dashboard_views.xml",
        "views/pm_schedule_views.xml",
        "views/flat_checklist_views.xml",
        'wizard/asset_inspection_wizard_view.xml',
        'wizard/asset_inspection_material_wizard_view.xml',
        'wizard/asset_material_rejection_wizard_view.xml',
        'wizard/asset_inspection_complete_wizard_view.xml',
        'wizard/job_order_complete_wizard_view.xml',
        'wizard/maintenance_task_team_wizard_view.xml',
        'views/asset_inspection_views.xml',
        'views/helpdesk_ticket_views.xml',
        'views/job_order_views.xml',
        'report/asset_inspection_report.xml',
        'report/report_job_order.xml',
        "views/asset_menu.xml",
        "data/asset_pm_cron.xml",
        "data/email_template_material_request.xml",
    ],
    'assets': {
        'web.assets_backend': [
            'asset_management/static/src/css/cafm_dashboard.css',
            'asset_management/static/src/js/cafm_dashboard.js',
            'asset_management/static/src/xml/cafm_dashboard.xml',
        ],
    },
    "application": True,
    "installable": True,
}
