{
    "name": "Asset Management",
    "version": "1.0",
    "summary": "Comprehensive Asset & CAFM Management",
    "description": """
     Standalone Asset Management app
    """,
    'author': 'Baramej® Business and Digital Technology Center LLC',
    'website': 'https://baramej.io/en',
    "category": "Operations/Assets",
    "depends": [
        "account",
        "account_asset",
        "mail",
        "maintenance",
        "stock",
        "hr",
        "helpdesk",
        "website",
        "sale_management", ],
    "data": [
        'security/asset_security.xml',
        "security/ir.model.access.csv",

        "views/asset_views.xml",
        "views/asset_location_views.xml",
        "views/report_maintenance_task.xml",
        "views/asset_maintenance_views.xml",
        "views/asset_service_ticket_views.xml",
        "views/cafm_dashboard_views.xml",
        "views/pm_schedule_views.xml",
        'wizard/asset_inspection_wizard_view.xml',
        'wizard/asset_schedule_task_wizard_view.xml',
        'wizard/asset_inspection_material_wizard_view.xml',
        'wizard/asset_material_rejection_wizard_view.xml',
        'wizard/asset_inspection_complete_wizard_view.xml',
        'views/asset_inspection_views.xml',
        'wizard/job_order_complete_wizard_view.xml',
        'wizard/maintenance_task_team_wizard_view.xml',
        'wizard/property_inspection_wizard_views.xml',
        'views/helpdesk_ticket_views.xml',
        "views/portal_job_order_template.xml",
        'views/job_order_views.xml',
        "views/asset_manpower_billing_views.xml",
        "data/asset_rca_data.xml",
        "views/asset_rca_views.xml",
        "views/portal_helpdesk_manager_approval.xml",
        "views/portal_contract_visit_report.xml",
        "views/portal_contractor_visit_form.xml",
        'report/asset_inspection_report.xml',
        'report/report_job_order.xml',
        "report/inspection_report.xml",
        "views/asset_menu.xml",
        "views/flat_checklist_views.xml",
        'data/helpdesk_job_categories.xml',
        'views/portal_ticket_form.xml',
        'views/asset_portal_company_views.xml',
        'views/res_config_settings_views.xml',
        'views/portal_employee_signup_templates.xml',
        'views/hr_employee_portal_views.xml',
        "data/asset_pm_cron.xml",
        "data/email_template_material_request.xml",
        "data/email_template_job_order.xml",

    ],
    'assets': {
        'web.assets_backend': [
            'asset_management/static/src/css/cafm_dashboard.css',
            'asset_management/static/src/js/cafm_dashboard.js',
            'asset_management/static/src/xml/cafm_dashboard.xml',
        ],
    },
    "application": True,
    "installable": True,
}
