from . import asset
from . import asset_location
from . import asset_maintenance
from . import asset_service_ticket
from . import asset_spare_part_line
from . import asset_tagging_wizard
from . import asset_move_wizard
from . import asset_assign_responsible_wizard
from . import helpdesk_inherit
from . import cafm_dashboard
from . import asset_inspection
from . import job_order
from . import product_extension
from . import asset_pm_schedule
from . import asset_maintenance_task_ext
from . import cron_pm_multi
from . import migration_pm_schedules
from . import flat_checklist
from . import asset_rca
from . import asset_manpower_billing
from . import helpdesk_portal_ticket